### ISSUE TITLE
dos not support redirect url 

### ISSUE THREAD

**Issue by oazya500** [hirohisa/ImageLoaderSwift#100]
could you please support redirected url 

if you open url http://market.mesbahey.com\imagefile\1DgdX3bTK3 it is redirect to image file and will fail to load image 

if you see this lib for android it is have more options and you can Benefits from it . It is Amazing lib for java app

https://github.com/nostra13/Android-Universal-Image-Loader

thanks in advance

**Comment by hirohisa** [comment]
Thanks, @oazya500 .

I will support it.

**Comment by hirohisa** [comment]
I released  0.12.2

**Comment by oazya500** [comment]
thanks allot
