### ISSUE TITLE
Disk().get("http://xxxxx.com/imagefile/Wg8iaA5Gfb" always nil 

### ISSUE THREAD

**Issue by oazya500** [hirohisa/ImageLoaderSwift#104]
I want to check if image in disk cach and always return nil

**Comment by oazya500** [comment]
when call like this all is work fine 

 Disk().set(data, forKey: "http://xxxxx.com/imagefile/Wg8iaA5Gfb".imageLoaderURL);


 Disk().set(data, forKey: "http://xxxxx.com/imagefile/Wg8iaA5Gfb".imageLoaderURL);

Disk().get(""http://xxxxx.com/imagefile/Wg8iaA5Gfb"".imageLoaderURL)

plz update this issues

**Comment by hirohisa** [comment]
it is fixed when I re-implemented for swift 4.0
