### ISSUE TITLE
Error with Data+ImageLoader in pods

### ISSUE THREAD

**Issue by raphahenrique** [hirohisa/ImageLoaderSwift#116]
I'm constantly getting this error in the Data+ImageLoader.swift after installing the pods
`Expression pattern of type '[Int]' cannot match values of type '[UInt8]'`

Anyone have any idea what might be ?

I already did a pod repo update, pod update, deleted podfile.lock and pods folder

![aaaaaaaa](https://user-images.githubusercontent.com/8950122/41159005-617ace40-6b01-11e8-899e-e1a16cceaf41.png)

**Comment by hirohisa** [comment]
@raphahenrique , I try to `pod install` and I can build app.

Env.:
Xcode9.4
CocoaPods : 1.5.3
Swift4.1

**Comment by raphahenrique** [comment]
I must be unlucky then :( ,`pod install` changes nothing. Don't know which configuration might be wrong.

Env.:
Xcode 9.2
Cocoapods 1.5.3
ImageLoader 0.14.0
Swift 4.0
