### ISSUE TITLE
Invalid CGBitmapContext

### ISSUE THREAD

**Issue by camdub** [hirohisa/ImageLoaderSwift#12]
I receive the following warning when using this library:

`CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.` 

This is on line `81` of `ImageLoader.swift`.

**Comment by hirohisa** [comment]
@camdub  Thanks for issue. Fixed it by https://github.com/hirohisa/ImageLoaderSwift/pull/13

**Comment by mpclarkson** [comment]
This is still a problem  in line 81 of ImageLoader.swift

**Comment by hirohisa** [comment]
@mpclarkson  Thanks for a comment.
Do you have warning or error logs for this issue?

I think the issue is fixed by https://github.com/hirohisa/ImageLoaderSwift/blob/master/ImageLoader/ImageLoader.swift#L43 .

**Comment by mpclarkson** [comment]
Sorry for the late response. Yes, I'm getting the following errors:

Apr 20 11:23:36 Matts-Macbook-Pro.local Hilenium[6159] <Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaLast; 832 bytes/row.
Apr 20 11:23:36 Matts-Macbook-Pro.local Hilenium[6159] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Apr 20 11:23:36 Matts-Macbook-Pro.local Hilenium[6159] <Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by hirohisa** [comment]
Thank you for error logs, @mpclarkson .

Fixed it by https://github.com/hirohisa/ImageLoaderSwift/pull/26

**Comment by hirohisa** [comment]
I bump version to `0.3.2`, include fixing this issue

**Comment by mpclarkson** [comment]
Thanks. I've updated my podfile and it seems to be fixed. Thanks for your responsiveness!

**Comment by hirohisa** [comment]
Thanks!
