### ISSUE TITLE
Fatal error if url has spaces

### ISSUE THREAD

**Issue by AlexeyFreelancer** [hirohisa/ImageLoaderSwift#27]
Hi @hirohisa 

I got fatal error for url: 
```
http://img.banggood.com/thumb/gallery/upload/2012/panxihua/SKU113576/yuan/SKU113576 (1).jpg
```

Screenshot: https://www.dropbox.com/s/3c7le7t8gps6758/Screenshot%202015-06-18%2019.15.54.png?dl=0

Best regards,
Alexey

**Comment by AlexeyFreelancer** [comment]
I understand that it's not a library issue, but will be perfect to fix it inside the library.
Some links:
 - http://stackoverflow.com/questions/1441106/nsdata-nsurl-url-with-space-having-problem
 - http://stackoverflow.com/questions/5560918/cannot-load-a-nsurl-with-spaces-or-hashtags-in-iphone-app
 - http://stackoverflow.com/questions/5845425/spaces-in-a-nsurl-with-variables-doesnt-load

**Comment by hirohisa** [comment]
Thank you for issue, @AlexeyFreelancer .
I will try to do it.

**Comment by hirohisa** [comment]
fixed by https://github.com/hirohisa/ImageLoaderSwift/commit/20ef32ff715dd1470276040b906ad5b24e893aac

**Comment by hirohisa** [comment]
Thank you

**Comment by AlexeyFreelancer** [comment]
You're welcome
