### ISSUE TITLE
Allow pre-rendering downloaded image data

### ISSUE THREAD

**Issue by ibru** [hirohisa/ImageLoaderSwift#30]
I'm having collection cells which contain 8 UIImageViews and their scrolling performance is very bad. Instruments shows most of the time is spent on image rendering.

I found an [article elaborating on this](http://www.nsprogrammer.com/2013/10/easy-uitableview-buffering.html#uitv_sec3) saying that when transforming NSData into UIImage, data can be pre-rendered so that UIImage gets shown faster.
This requires creating UIImage differently then calling `UIImage(data: receivedData)`.

Could your lib include a way to inject custom asynchronous way of creating UIImage from downloaded data? Or maybe it could automatically include this pre-rendering feature?
What do you think?

**Comment by ibru** [comment]
I've modified the my local copy of your lib little bit to support async image rendering:

Added new closure property to `Manager`:
```
    public var imageRenderingBlock: ((imageData: NSData, completion: (image: UIImage?) -> Void) -> Void) = {(imageData, completion) in
        completion(image: UIImage(data: imageData))
    }
```

Now I can render `UIImage` asynchronously, when request is completed (in `Loader.complete(:)`)
```
            if error == nil {
                delegate.imageRenderingBlock(imageData: receivedData, completion: { (image) -> Void in
                    self._toCache(URL, image: self.receivedData)
                    
                    for block: Block in self.blocks {
                        block.completionHandler(URL, image, error)
                    }
                    self.blocks = []
                })
            }
```

I had to however also change caching to cache `NSURL:NSData` pairs, not `NSURL:UIImage` to be able to asynchronously load also cached images. Now I can load cached image like this (in `extension UIImageView._load(::)`):

```
        // caching
        if let imageData = Manager.sharedInstance.cache[URL] {
            Manager.sharedInstance.imageRenderingBlock(imageData: imageData, completion: { (image) -> Void in
                completionHandler(URL, image, nil)
            })
            return
        }
```

In my AppDelegate I then define custom rendering:
```
        ImageLoader.Manager.sharedInstance.imageRenderingBlock = {(imageData, completion) in
            // render UIImage asynchronously, see http://www.nsprogrammer.com/2013/10/easy-uitableview-buffering.html#uitv_sec3
            UIImage.imageByRenderingData(imageData, completion: { (image) -> Void in
                completion(image: image)
            })
        }
```

What do you think about this solution?
I can clean up the code little bit and send a pull request if this is good approach to the problem.

**Comment by hirohisa** [comment]
Thanks @ibru .

I think the solution for decompressing is better too. I dont want to implement custom block, because this is not simple, usage of ImageLoader is affected.

I try to implement https://github.com/hirohisa/ImageLoaderSwift/pull/31.
