### ISSUE TITLE
Image size downloaded not true for the first time after upgrading to 0.6.1

### ISSUE THREAD

**Issue by gloryluu** [hirohisa/ImageLoaderSwift#45]
cell.contentImageView.load(URL, placeholder: nil, completionHandler: {[weak self]
                URL, image, error, cacheType in
                if let weakSelf = self, image = image {
                    print("image size w:\(image.size.width), h:\(image.size.height)")
                    // Do something with image
                }
 })
image link: https://files.parsetfss.com/d1c4d42b-52b9-427b-98f8-a9d816751efd/tfss-29090e17-fd55-4959-891e-a3134d84152f-seBCKRC2qQ.png 
This is them sample code I am using. The problem doesn't happen in 0.5.1, that the image size is downloaded as full size (500x325) by observe the log. After pull 0.6.1 I found the problem that the image size in log line is divided by 2, mean (250x162.6), so the image displayed with wrong size.
Wrong size issue of the image only happen if the is not downloaded yet. If it is already cached, thing is good. 
Hope you can help me.
Thanks.

**Comment by hirohisa** [comment]
Thank you for the issue, @gloryluu.
It is a bug.
- I change from saving inflated image to cache(0.5.1) to saving raw image that is fetched (0.6.1).
I will remove property inflatesImage.

**Comment by hirohisa** [comment]
fixed by https://github.com/hirohisa/ImageLoaderSwift/commit/5fe2c0e5647033e12af74f67dc594fde32f6f2de

**Comment by hirohisa** [comment]
Try to use version to 0.6.2, size is correct(500x325).
Thanks.

**Comment by gloryluu** [comment]
Thanks you. I take the update and bug is gone now.

**Comment by gloryluu** [comment]
Hi Hirohisa,

I have a question, in what case the downloaded image is put in the folder
name: swift.imageloader.diskcached ? Since I notice that the image is put
outside the cache folder, whose name pattern is smt like:
swift.imageloader.diskcached_URL_
I attached the image. Thanks.

Regards,


​

**Comment by hirohisa** [comment]
Thanks @gloryluu !!
It's bug, fixed by https://github.com/hirohisa/ImageLoaderSwift/commit/d17a32119a98e8c75b727dba381c0c32e709dcec
