### ISSUE TITLE
Transparent background images become white?

### ISSUE THREAD

**Issue by gloryluu** [hirohisa/ImageLoaderSwift#53]
I got that problem while testing the downloading:

moodImageView.load("http://mooddy.officience.com/uploads/media/default/564e/91/thumb_564e9152582c2ee3217b23c6_default_small.png")

The problem doesnt happen if I use this: 

let url = NSURL(string:"http://mooddy.officience.com/uploads/media/default/564e/91/thumb_564e9152582c2ee3217b23c6_default_small.png")!
moodImageView.image = UIImage(data: NSData(contentsOfURL: url)!)

**Comment by hirohisa** [comment]
Thanks, @gloryluu .

I fixed by https://github.com/hirohisa/ImageLoaderSwift/commit/d761b61b04257c07b24cabab0089041d2f4a30ef.

**Comment by hirohisa** [comment]
And now I bump version 0.7.2.
It has this commit, please use.

Regards

**Comment by gloryluu** [comment]
Hi Hirohisa,

I dont know if it helps you but I got some crashes ra randomly. Quite hard
to reproduce.

Regard,

On Tue, Nov 24, 2015 at 6:07 PM, Hirohisa Kawasaki <notifications@github.com

**Comment by hirohisa** [comment]
Hi @gloryluu ,
Could you show me crash logs?

**Comment by gloryluu** [comment]
Sorry I didnt see any log in the simulator. It keeps crashing randomly.
Right at the position I show you, always exc_bad_access.
