### ISSUE TITLE
Xcode cannot find `ImageLoader`

### ISSUE THREAD

**Issue by gaudecker** [hirohisa/ImageLoaderSwift#74]
Loading an image is done with a free function `load` instead of `ImageLoader.load`. The readme should probably be updated.

Thank you! :heart:

**Comment by hirohisa** [comment]
Thanks, @gaudecker .
I added `import ImageLoader`

Fix by https://github.com/hirohisa/ImageLoaderSwift/commit/84fd34002f3faa7f7fbc89c8ecad6a0ba088934d

**Comment by djdance** [comment]
BTW it wont work without import ImageLoader
