### ISSUE TITLE
Change loaded image

### ISSUE THREAD

**Issue by bashan** [hirohisa/ImageLoaderSwift#75]
Is there an option of changing the loaded image? For example, I need to crop the image for a specific size. Here is my current code which doesn't work:

        cell.courseImageView.load(course.imageUrl, placeholder: nil) { URL, image, error, cacheType in
            if let anImage = image {
                let croppedImage = Util.imageByCroppingImage(anImage, size: cell.frame.size)
            
                if cacheType == CacheType.None {
                    let transition = CATransition()
                    transition.duration = 0.5
                    transition.type = kCATransitionFade
                    cell.courseImageView.layer.addAnimation(transition, forKey: nil)
                }
            
                cell.courseImageView.image = croppedImage
            }
        }
        
        return cell
    }

**Comment by hirohisa** [comment]
Thank you, @bashan .

I will investigate it. By the way, do you use automaticallyAdjustsSize? It's autoresize property.

**Comment by bashan** [comment]
No, How can I use it? Where can it be set?

Please note, that I need the image to be cropped from the center and not just scaled.

**Comment by hirohisa** [comment]
Sorry, I did not explain enough.

First,
Is there an option of changing the loaded image? No. I will investigate it and fix https://github.com/hirohisa/ImageLoaderSwift/pull/76.

Second,
`automaticallyAdjustsSize` that is ImageLoader's property automatically controls to an image size to small with `contentMode`.

I will note about changelog and more to README.
Thank you.

**Comment by hirohisa** [comment]
merged https://github.com/hirohisa/ImageLoaderSwift/pull/76
