### ISSUE TITLE
No option to disable url encoding

### ISSUE THREAD

**Issue by badunk** [hirohisa/ImageLoaderSwift#79]
I have urls that have already been url encoded and I wish to load it through the library.

Unfortunately, I think an earlier commit (https://github.com/hirohisa/ImageLoaderSwift/commit/20ef32ff715dd1470276040b906ad5b24e893aac) is causing it to assume all urls are raw.

My use case is actually quite common and simple I think.  I have a webservice that is signing expiring images hosted from amazon s3.  Amazon s3 notoriously uses a lot of url-unsafe characters in its signatures, including the literal `%`.  However, it intends that clients send a literal `%` and not the url-encoded form of `%25` - the extra 2 characters break the signature

This is the line that is doing the conversion.
https://github.com/hirohisa/ImageLoaderSwift/blob/20ef32ff715dd1470276040b906ad5b24e893aac/ImageLoader/ImageLoader.swift#L24

**Comment by hirohisa** [comment]
Thanks, @badunk .
I will investigate this issue.

**Comment by maeldur** [comment]
I ran into this too @badunk and it seems to work fine if you pass in NSURL(string:<pre-encoded url string>) into .load() instead of the string directly

**Comment by badunk** [comment]
ah of course, thanks @maeldur!

**Comment by hirohisa** [comment]
Thanks, @maeldur !

**Comment by hirohisa** [comment]
Sorry, I'm late.
Fix by #84 and use 0.9.0

e.g.
```
Disk.get(URL.absoluteString.escape())
```
