### ISSUE TITLE
Support for etags and authentication

### ISSUE THREAD

**Issue by ogezue** [hirohisa/ImageLoaderSwift#81]
-In my app the image can be outdated if the user has uploaded a new image from himself. Does you lib support etags so that the library handles outdated images by itself?

-Would it be possible to set login credentials in your lib that will be used with every request?

**Comment by hirohisa** [comment]
Hi, @ogezue .

First, this library still support etags.
Second, this library doent set login credentials every time. I will investigate.

**Comment by ogezue** [comment]
Hi @hirohisa,

thank you very much! Supporting etags is something that makes your (Swift)-lib unique.
