### ISSUE TITLE
Collectionview of images scrolling not smooth

### ISSUE THREAD

**Issue by ogezue** [hirohisa/ImageLoaderSwift#83]
I have a collectionview showing  round about 10 images at the same time with one cell per image. 

This is how I set the image:

```
        imageView.load(photo.lowResUrl, placeholder: placeHolderImage) { URL, image, error, cacheType in
            
            if cacheType == CacheType.None {
                let transition = CATransition()
                transition.duration = 0.5
                transition.type = kCATransitionFade
                self.imageView.layer.addAnimation(transition, forKey: nil)
                self.imageView.image = image
            }
        }
```

But the scroll experience is not very good on an iPhone 6s. This is caused through the transition. Is there anything that can be optimized?

**Comment by hirohisa** [comment]
Thanks, @ogezue .
Sorry, I'm late.
Fix by https://github.com/hirohisa/ImageLoaderSwift/pull/84 and use `0.9.0`

**Comment by Urkman** [comment]
This is still very crappy... 
On an iPad Air with 3 Image per row...
