### ISSUE TITLE
How do i use cache with this library?

### ISSUE THREAD

**Issue by cosmo1234** [hirohisa/ImageLoaderSwift#90]
I have this piece of code here 
` func setupViews(food: Food, img:UIImage?){
        self.food = food
        resturantName.text = food.store_name
        timeLabel.text = food.time + " min"
        
        ImageLoader.load(food.imageString!).completionHandler { (url, image, error, cache) in
        
            if error != nil{
                print("image empty")
            }else{
                self.foodImage.image = image
            }
        }`

But when the app is loaded not all the images are loaded and also i don't think it is caching

**Comment by hirohisa** [comment]
type of `cache` is from disk or network.
FYI: https://github.com/hirohisa/ImageLoaderSwift/pull/35
