### ISSUE TITLE
Swift 3 cocoapod issue

### ISSUE THREAD

**Issue by AntonijoDev** [hirohisa/ImageLoaderSwift#91]
Hi,
I have a problem while trying to download swift version of ImageLoaderSwift. It looks like it is downloading <Swift 3.0. Do I need to change the podfile in some other wah to get swift 3.0 version?

**Comment by hirohisa** [comment]
Thank you for the issue.
I used cocoapods old version. I forgot .swift-version.

So, I bumped versions.
- 0.10.1, swift2.3
- 0.11.1, swift3.0
