### ISSUE TITLE
Images sometimes don't load

### ISSUE THREAD

**Issue by AntonijoDev** [hirohisa/ImageLoaderSwift#92]
I am xCode 8.0, Swift3 configuration

From my app I am using this call:
cardImage.load("Some url", placeholder: placeholder)

First time the image loads OK, but sometimes it fails when loading from cache. I have isolated the problem in imageLoader_load method. Sometimes the 
**if let wSelf = self, let selfUrl = wSelf.url, let image = image , selfUrl == url {**
condition failes. When I brek it down on lines it failes on   **selfUrl == url** part. I can't really explain why because I don't see error in your code. I fixed it by excluding this part of condition from code. I believe that this condition is introduced as a fail safe cause the process of downloading is asynchronous and the method can be called from table views which use reusable cells or something like that. 

Also I have a suggestion:
Can you please make image transition modular from outside, and remove condition **cacheType == CacheType.none** cause I woud like to animate transition no matter if the image comes from the cache, or at least make it optional.

thx

**Comment by petard** [comment]
I have similar issue with an UITableView (Swift3, XCode 8.1), with the images appearing but then not being visible after scrolling.

**Comment by hirohisa** [comment]
Thank you for the issue.
I fix by https://github.com/hirohisa/ImageLoaderSwift/pull/95
I will release 0.12.0.

**Comment by hirohisa** [comment]
I released 0.12.0
