### ISSUE TITLE
Placeholder Image ? 

### ISSUE THREAD

**Issue by kamalupasena** [hirohisa/ImageLoaderSwift#97]
I wonder what happen to the placeholder image in 0.12.0

**Comment by EralpB** [comment]
I wonder as well..

**Comment by hirohisa** [comment]
Sorry, I will supprt placeholder.

**Comment by hirohisa** [comment]
fix #98 , I released version to 0.12.1.

**Comment by kamalupasena** [comment]
did u released it on pod ?

**Comment by hirohisa** [comment]
oh, sorry, I forgot to deploy on pod.

I released
